### ISSUE TITLE
builtin export

### ISSUE THREAD

**Issue by willtrigo** [vinicius-f-pereira/minishell#38]
- [x] Showing env vars "_=".
- [x] when you "export =asddasd" you add "=asdasd" as a variable of env.
- [ ] you can improve output of error message putting the name of "=asddasd" as "export: `=asddasd': not a valid identifier"(but this is detail, only the 2 first are real a true issue).

**Comment by 0bvim** [comment]
Thanks bro... The first error I can't reproduce. You can send evidences or how to reproduce, please? The second I fixed in this pr #40 and third I'll not fix. I'll let it to 42sh hahahahah
